title: 记事本
description: > # this means to ignore newlines until "baseurl:"
    记录一些平时折腾的东西
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://linshaoyong.github.io"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: linshaoyong
author-img: blade.jpg # add your photo
about-author: 程序员
twitter: linshaoyong
facebook: linshaoyong
github: linshaoyong
linkedin: 少勇-林-7232483b
email: linshaoyong@gmail.com

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: UA-126399136-1

# Build Settings
markdown: kramdown

plugins:
   - jemoji
   - jekyll-sitemap
   - jekyll-paginate
   - jekyll-feed
   - github-pages

paginate: 8
paginate_path: "/page/:num"

exclude:
  - Gemfile
  - Rakefile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - yarn.lock
  - package.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
